language: c

env:
    - SMVERSION=1.6.1

matrix:
    fast_finish: true
    
before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib 
    - sudo apt-get install lynx
    - sudo apt-get install curl

before_script:
    - wget http://cdn.probablyaserver.com/sourcemod/sourcemod-1.6.1-linux.tar.gz -O sm.tgz
    - tar -xzf sm.tgz
    - rm addons/sourcemod/scripting/*.sp
    - rm -R addons/sourcemod/plugins/*
    - cp -Rv scripting/* addons/sourcemod/scripting/
    - TF2ITEMSURL="http://builds.limetech.org/files/"
    - TF2ITEMSPATTERN="http:.*tf2items-.*-.*-linux.zip"
    - TF2ITEMSPACKAGE=`lynx -dump "$TF2ITEMSURL" | egrep -o "$TF2ITEMSPATTERN" | tail -1`
    - wget $TF2ITEMSPACKAGE
    - unzip $(basename "$TF2ITEMSPACKAGE")
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh

script: 
    - ./compile.sh

after_script:
    - cd compiled/
    - wget -O pomf.sh https://gist.githubusercontent.com/chauffer/a7d4d290840d80e97924/raw/34870d5b9566f5b2c6364d35d6887bc7f0565b0a/gistfile1.txt
    - chmod +x pomf.sh
    - for i in $(ls *.smx); do ./pomf.sh $i; done
